### ISSUE TITLE
Updating Link Text- Accessibility

### ISSUE THREAD

**Issue by rstarowicz** [dlab-berkeley/MAXQDA-Fundamentals#1]
Let's update the text to the following instead:

This repository contains the materials for D-Lab MAXQDA Fundamentals workshop.  See the following links to access the materials:

Materials Folder [link](https://drive.google.com/drive/folders/1l7I0nOHeFrcEYRaLM71lXgYVxjZQkJK7?usp=share_link).
MAXQDA Fundamentals Google Slides [link](https://docs.google.com/presentation/d/1rJ_5iOhRzBM5M-RqYoT3NojAhq-hUFwc/edit?usp=share_link&ouid=113225142021726469601&rtpof=true&sd=true).
PDF Version of MAXQDA Fundamentals Slides [link](https://drive.google.com/file/d/1_QspynmxEWagKpShtUC0WwvhYmFhqVSi/view?usp=share_link).

**Comment by pssachdeva** [comment]
This is to improve accessibility, right? just to be clear, is this preferable to making the entire bullet a link, i.e. 

[Materials Folder](https://drive.google.com/drive/folders/1l7I0nOHeFrcEYRaLM71lXgYVxjZQkJK7?usp=share_link)

vs. 

Materials Folder [link](https://drive.google.com/drive/folders/1l7I0nOHeFrcEYRaLM71lXgYVxjZQkJK7?usp=share_link)

**Comment by rstarowicz** [comment]
Yes that’s correct! Making the entire bullet the linked text.Thank you, PratikiPhone. iTypos. iApologize. On Jan 9, 2023, at 3:16 PM, Pratik Sachdeva ***@***.***> wrote:﻿
This is to improve accessibility, right? just to be clear, is this preferable to making the entire bullet a link, i.e.
Materials Folder
vs.
Materials Folder link
