### ISSUE TITLE
Include resources in README

### ISSUE THREAD

**Issue by pssachdeva** [dlab-berkeley/MAXQDA-Fundamentals#3]
Other D-Lab Workshop READMEs have a list of resources. We should add one for MAXQDA and other qualitative software for this README.

**Comment by rstarowicz** [comment]
Yes, I can add this and some text that will also provide "Installation Instructions." If you add me as a collaborator will I be able to edit the ReadMe directly like I can in the Stata Fundamentals GitHub?

**Comment by pssachdeva** [comment]
I just gave the curriculum-development group Maintain status, so you should be able to edit.

**Comment by rstarowicz** [comment]
@pssachdeva Thank you! The resources and installation information is added.
